[package]
name = "pkmnt"
version = "0.1.0"
authors = ["Andreas Burg <andreas.burg@gmx.net>"]
license = "MIT"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
ratatui = "0.26.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
